version: "3.8"
services:

  grafana:
    image: grafana/grafana:10.2.2
    ports:
      - 0.0.0.0:3000:3000/tcp
    volumes:
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
      - ./grafana/provisioning/:/etc/grafana/provisioning/
      - ./grafana/dashboards/:/var/lib/grafana/dashboards/
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:v2.48.0
    ports:
      - 9090:9090/tcp
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
    ports:
      - 8000:80/tcp
    restart: unless-stopped

  backend:
    build:
      context: ./backend
    environment:
      POSTGRESQL_CONNECTION_URL: postgres://postgres:password@postgres:5432/postgres
    ports:
      - 5000:5000/tcp
      - 5001:5001/tcp
    restart: unless-stopped

  postgres:
    image: postgres:16.1-alpine3.18
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432/tcp
    restart: unless-stopped

  bot:
    build: ./bot
    environment:
      BACKEND: http://host.docker.internal:5000
    restart: unless-stopped
