{
 "title": "Database",
 "tags": [ "todos" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "query",
    "query": {
     "query": "label_values(app_query_duration_seconds_count, query)"
    }
   },
   { "name": "min_interval", "query": "20s" }
  ]
 },
 "panels": [
  { "title": "$query", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "query" },
  {
   "title": "Calls",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by (query) (rate(app_query_duration_seconds_count{query=\"$query\"}[$__rate_interval]))",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Average Time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(app_query_duration_seconds_sum{query=\"$query\"}[$__rate_interval])) / sum(rate(app_query_duration_seconds_count{query=\"$query\"}[$__rate_interval]))",
     "legendFormat": "average"
    }
   ]
  },
  {
   "title": "Quantiles",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.25, sum by (le) (rate(app_query_duration_seconds_bucket{query=\"$query\"}[$__rate_interval])))",
     "legendFormat": "25th"
    },
    {
     "expr": "histogram_quantile(0.50, sum by (le) (rate(app_query_duration_seconds_bucket{query=\"$query\"}[$__rate_interval])))",
     "legendFormat": "50th"
    },
    {
     "expr": "histogram_quantile(0.75, sum by (le) (rate(app_query_duration_seconds_bucket{query=\"$query\"}[$__rate_interval])))",
     "legendFormat": "75th"
    },
    {
     "expr": "histogram_quantile(0.95, sum by (le) (rate(app_query_duration_seconds_bucket{query=\"$query\"}[$__rate_interval])))",
     "legendFormat": "95th"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (le) (rate(app_query_duration_seconds_bucket{query=\"$query\"}[$__rate_interval])))",
     "legendFormat": "99th"
    }
   ]
  }
 ]
}